[tool.black]
target-version = ["py310"]

[tool.poetry]
name = "coverage-comment"
version = "0.0.0"
description = "Publish diff coverage report as PR comment, and create a coverage badge to display on the readme, for Python projects."
authors = ["Joachim Jablon <ewjoachim@gmail.com>"]
license = "MIT License"
packages = [
    { include = "coverage_comment" },
]
include = ["coverage_comment/default.md.j2"]

[tool.poetry.scripts]
coverage_comment = 'coverage_comment.main:main'

[tool.poetry.dependencies]
python = "^3.10"
coverage = {version = "*", extras = ["toml"]}
diff-cover = "*"
httpx = {version = "*", extras = ["http2"]}
Jinja2 = "*"

[tool.poetry.dev-dependencies]
isort = "*"
black = "*"
mypy = "*"
flake8 = "*"
pytest = "*"
pytest-mock = "*"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
